Fix when cwd is None
rraval/pew pull request #3
Opened 2022-03-14 15:21 UTC by deepio

Becomes a problem in python `3.9.9`

2022-03-15 13:34 UTC, rraval requested changes

2022-03-15 13:34 UTC, rraval commented on pew/pew.py
> -                os.chdir(kwargs['cwd'])
Catching `TypeError` is kind of roundabout.

Why not:

```
os.chdir(kwargs['cwd'] or os.getcwd())
```

2022-03-15 16:06 UTC, deepio commented on pew/pew.py
> -                os.chdir(kwargs['cwd'])
That's much better

2022-03-16 13:20 UTC, rraval approved these changes

2022-03-16 13:22 UTC, merged